name: Lint ğŸ§¶

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  build:
    name: SuperLinter ğŸ¦¸ğŸ»â€â™€ï¸
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      # To report GitHub Actions status checks
      statuses: write

    steps:
      - name: Checkout Repo ğŸ›ï¸
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      - name: Super-linter ğŸ¦¸ğŸ»â€â™€ï¸
        uses: super-linter/super-linter@2757a99ca5ce4642797fd2187a068c28f10acb3b
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JAVASCRIPT_STANDARD: true
          FIX_JAVASCRIPT_STANDARD: true
          VALIDATE_JAVASCRIPT_PRETTIER: true
          FIX_JAVASCRIPT_PRETTIER: true
